### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jack11e** [useragents/Zefoy-TikTok-Automator#11]
it keeps saying error while importing modules from requierments.txt when i already installed them

**Comment by unlaid** [comment]
make sure you cd'd with cmd into the folder the py file is in, also make sure its extracted and chromedriver.exe is in the folder with the python file.

**Comment by useragents** [comment]
You may have 2 Python versions installed, please delete one and keep one. The modules may have been installed to the wrong Python and you are running the script with the other Python.
