### ISSUE TITLE
Error in second attempt

### ISSUE THREAD

**Issue by shimjitsu** [useragents/Zefoy-TikTok-Automator#16]
The first attempt works, but after cool down timer, on likes, share, view or followers, the bot just doesn't work on 2nd attempt even the cooldown time is cleared off in zefoy.

**Comment by hanisrdsaf** [comment]
how did u open it? for me its just a notepad file

**Comment by shimjitsu** [comment]
> how did u open it? for me its just a notepad file

Download python, install it and download the requirements in txt file.

**Comment by useragents** [comment]
Is there any specific error? Seems to be working perfectly on my end.
