### ISSUE TITLE
Still have to manually click on views and then paste the url 

### ISSUE THREAD

**Issue by killerlux** [useragents/Zefoy-TikTok-Automator#17]
Hello,
After running the python file , I type 3 for views and then paste the link and then answer the captcha.
It redirects me to zefoy website and doesn't automate anything.It's like I opened it in my own chrome window.

**Comment by useragents** [comment]
Is there any specific error? This script appears to be working perfectly from my end.

**Comment by useragents** [comment]
Closed due to inactivity.
