### ISSUE TITLE
this is why

### ISSUE THREAD

**Issue by Spro1121** [useragents/Zefoy-TikTok-Automator#19]
![image](https://user-images.githubusercontent.com/105527512/168405855-62c48e45-a9ba-4419-b577-8d66dea1495b.png)

**Comment by codeuk** [comment]
download chromedriver and put it in the same directory

**Comment by useragents** [comment]
Please read the usage in the [README.md](https://github.com/useragents/Zefoy-TikTok-Automator/blob/main/README.md).
