### ISSUE TITLE
Error trying to load web driver: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

### ISSUE THREAD

**Issue by DonGrentrox** [useragents/Zefoy-TikTok-Automator#20]
Hey useragents, i installed a chrome driver, downloaded it and put it in the folder where tiktok.py is. This message still pops up after that: Error trying to load web driver: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
Could you help me? Thanks in advance

**Comment by useragents** [comment]
This is unrelated to my script, but ensure that the ZIP is extracted and that the chromedriver.exe is in the same folder. If the problem is still happening, try put the chromedriver.exe in your C: drive.
