### ISSUE TITLE
Says the chrome driver must be in the path and I put it there still not working

### ISSUE THREAD

**Issue by Jaydxn133** [useragents/Zefoy-TikTok-Automator#34]

**Comment by Proxitimy** [comment]
idk why it does that

**Comment by besteryoutubee** [comment]
it says too for me

**Comment by HeyItsSloth** [comment]
You can fix it by copying the "chromedriver.exe" into the same folder as the tiktok.py file, then dragging chromedriver onto tiktok.py

**Comment by useragents** [comment]
It has to be in the same folder
