### ISSUE TITLE
Possible to Mass-Unlike all Tik-Tok Likes?

### ISSUE THREAD

**Issue by GitHubQueenn** [useragents/Zefoy-TikTok-Automator#38]
I am using this script: https://github.com/frxangelz/tiktokunliker

The problem? It keeps getting stuck on "Unliked : (number here), Waiting For 14 seconds to reload" but never reloads and the times it does reload, it doesn't click over to the Liked tab, only the main profile page. Developer seems to be MIA so I have no idea how to make it work without me babysitting it and manually going to my liked tab every 2-3mins. 20k likes to go through...

**Comment by FlipfudgeV2** [comment]
you aint got the accs, how you unlike

**Comment by useragents** [comment]
You make an issue on my github that’s not even my script and expect a fix?
