### ISSUE TITLE
modules in requirements.txt

### ISSUE THREAD

**Issue by hakrawy** [useragents/Zefoy-TikTok-Automator#40]
Error while importing modules. Please install the modules in requirements.txt
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Zefoy-TikTok-Automator-main\tiktok.py", line 12, in <module>
    init(convert = True, autoreset = True)
NameError: name 'init' is not defined

**Comment by zakie29** [comment]
> Error while importing modules. Please install the modules in requirements.txt Traceback (most recent call last): File "C:\Users\user\Desktop\Zefoy-TikTok-Automator-main\tiktok.py", line 12, in init(convert = True, autoreset = True) NameError: name 'init' is not defined

same error

**Comment by dkfnfkdnk** [comment]
have the same problem

**Comment by useragents** [comment]
You obviously modified the file. Download the latest version
