### ISSUE TITLE
Error chrome driver 

### ISSUE THREAD

**Issue by Packm12** [useragents/Zefoy-TikTok-Automator#41]
████████▀▀▀████
                ████████────▀██
                ████████──█▄──█
                ███▀▀▀██──█████
                █▀──▄▄██──█████
                █──█████──█████
                █▄──▀▀▀──▄█████
                ███▄▄▄▄▄███████ github.com/useragents

                [Error] Error trying to load web driver: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
                
                Ps : my version is: 107.0.5304.87 and it is not available on the site: https://chromedriver.chromium.org/downloads to install it (it is the latest).

**Comment by UserKurd** [comment]
Yes Its This Error 
please help me

**Comment by useragents** [comment]
For windows, you need to download a chrome driver with the same version and put it in the same folder as the bot.
