### ISSUE TITLE
Error message for chrome driver

### ISSUE THREAD

**Issue by rahilalbert** [useragents/Zefoy-TikTok-Automator#44]
Error trying to load web driver: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by mdalsi** [comment]
Could you please provide more information? Are you on Windows, Mac or Linux? On windows you should be able to run it simply putting the chromedriver.exe file in the bot folder, on linux you just need to install chromedriver (or download it) and tell the script where to find it (I did it using `export PATH=$PATH:/home/user/Downloads`).

**Comment by useragents** [comment]
Couldn’t of been explained better by @mdalsi
