### ISSUE TITLE
how i slove this problem

### ISSUE THREAD

**Issue by Nabster0727** [useragents/Zefoy-TikTok-Automator#47]
![Capture d’écran 2022-11-30 173201](https://user-images.githubusercontent.com/119460119/204854892-b00605ae-96c8-4f86-8ee5-7445acf852f8.JPG)

**Comment by clankie83** [comment]
Hello, I'm having the same issue

**Comment by marcos1233215** [comment]
> ![Capture d’écran 2022-11-30 173201](https://user-images.githubusercontent.com/119460119/204854892-b00605ae-96c8-4f86-8ee5-7445acf852f8.JPG)

you don t have the same chrome version

**Comment by clankie83** [comment]
I have Chrome 107.0.5304.121 so I'm ChromeDriver 107.0.5304.62, and I have the same error message as OP.

**Comment by useragents** [comment]
I will add a fix soon.
