### ISSUE TITLE
Site never securing infinite loop please help

### ISSUE THREAD

**Issue by pitbullgio** [useragents/Zefoy-TikTok-Automator#49]
Gets stuck at the securing site page no clue why please help, code is on the bottom maybe someone can tell me what needs to be fixed
![Screenshot 2022-12-06 101549](https://user-images.githubusercontent.com/103554126/205950731-5ba6b4e0-1482-4730-a2eb-a040ab50dbc1.png)
![Screenshot 2022-12-06 104343](https://user-images.githubusercontent.com/103554126/205958232-a4182ade-fcab-49d2-8215-98e378dd4987.png)

**Comment by Isaquito9389** [comment]
I have the same problem

**Comment by useragents** [comment]
Fixed
