### ISSUE TITLE
no zip

### ISSUE THREAD

**Issue by powv** [useragents/Zefoy-TikTok-Automator#5]
theres no zip i done chromedriver, cmd prompt all that. However theres nothing to actually launch?

**Comment by wail564** [comment]
Yes same

**Comment by oneeegithub** [comment]
yall dumb. its not even released yet

**Comment by useragents** [comment]
Download the zip [here](https://github.com/useragents/Zefoy-TikTok-Automator/archive/refs/heads/main.zip).
@oneeegithub @wail564 @powv
