### ISSUE TITLE
Bad gateway 502

### ISSUE THREAD

**Issue by bigbrainhehe** [useragents/Zefoy-TikTok-Automator#52]
zefoy.com web doesnt load

**Comment by useragents** [comment]
You do realize this is an automator. Not the official Zefoy support page. 
This project is simply an automator and Zefoy.com is not owned by me.
If you even read the console it says this: 
![image](https://user-images.githubusercontent.com/103281345/206916816-cd9f96b3-7ad4-4f14-840a-b994445b58ae.png)
