### ISSUE TITLE
undetected_chromedriver problem

### ISSUE THREAD

**Issue by bgbob** [useragents/Zefoy-TikTok-Automator#57]
Hy there,

I've got this error,
![image](https://user-images.githubusercontent.com/44938218/209479606-82c97262-3b5b-4fe0-a6cc-115a30ab14c9.png)

I'm using Python 3.11 windows 64bit, allready installed all the driver needed

Is there any solution for this error message? thanks

**Comment by 7elmie** [comment]
First This is not one Error You have Many Error in different lines and You Trouble shooting  All error Step By step 

Start with the first error in Powershell window Command Read and Search about this First error maybe he is a Problem. 

But You need To solve all problems Sequence To Find the mastic

Start with the Beginning..
With My Best wishes.

**Comment by useragents** [comment]
What mode? Views/likes/etc?
Please provide more detail.
