### ISSUE TITLE
502 badgateway

### ISSUE THREAD

**Issue by HoodedGamer93** [useragents/Zefoy-TikTok-Automator#60]
what country vpn works? we cant get through

**Comment by useragents** [comment]
VPN doesn't work on Zefoy.

**Comment by HoodedGamer93** [comment]
its says i have to be from the right country so why not tell me what to do bud instead of closing the ticket. so basiclly we cant use the code cuz we not from a unstated country?? zefroy.com doesnt work either this code is burnt up

**Comment by HoodedGamer93** [comment]
i subscribe to you dont you want to keep subscribers real ones....

**Comment by useragents** [comment]
I do not own zefoy.com
If you are mad about them blocking your country and VPNs, that has nothing to do with me.

**Comment by useragents** [comment]
There is nothing I can do 😂

**Comment by HoodedGamer93** [comment]
lol ok but there no proxie or vpn that works u should prob state that in ur code bud im not mad ill just keep moving good luck bud this why i get code from trusted souces u legit wasted 5 hrs for me trying to figure this out hope that made ur day and u accomplished alot off it

**Comment by useragents** [comment]
@HoodedGamer93 It clearly says in my code 502 Bad Gateway = Blocked country or VPN blocked
![image](https://user-images.githubusercontent.com/103281345/210264523-94fe3ed1-a9f3-42e2-9ad4-2194f6f644fa.png)

And in the code [here](https://github.com/useragents/Zefoy-TikTok-Automator/blob/main/tiktok.py#L52)
