### ISSUE TITLE
scammers

### ISSUE THREAD

**Issue by HoodedGamer93** [useragents/Zefoy-TikTok-Automator#67]
scammers dont trust these ppl take down this code

**Comment by useragents** [comment]
`This user is calling a FREE project a "scam"`
Keep in mind this project is free. This user is very immature
You can read his issues here #60 

**I do NOT** own zefoy.com website. 
This user is mad that Zefoy blocked his country. 
He tried VPN and Zefoy also blocked that so this has nothing to do with me.

**Comment by HoodedGamer93** [comment]
instead of giving advice u closed the ticket and gave no real imput u dont need this code if u can just go to zefroy.com no need for this fake code and u were disrespectful off the jump anybody just go to zefroy.com if it doesnt work the code isnt going to work either doing all this coding is a waste of time if u can just go straigh to the website lmfao u added stuff to the code to scam ppl and trace there computers
