### ISSUE TITLE
chromedriver not found

### ISSUE THREAD

**Issue by x198x** [useragents/Zefoy-TikTok-Automator#8]
i have google chrome version 101 downloaded and the chromedriver is also the same version but it still says 'Error trying to load web driver'

**Comment by useragents** [comment]
Thanks to @anton-chernianu, you can use the code [here](https://github.com/useragents/Zefoy-TikTok-Automator/blob/5384e3b9193b8316231965537c131fbc7e1a8b30/tiktok.py) which will automatically install chromedriver for you.

**Comment by anton-chernianu** [comment]
@useragents yes, I have the same bug on macos ;-)
